version: '3'

services:
  database:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: innihald
    ports: [ 5432:5432 ]
    volumes:
    - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    ports: [ 6379:6379 ]

volumes:
  pgdata: